include ${GOROOT}/src/Make.inc

TARG=gorilla.googlecode.com/hg/gorilla/appengine/datastore

GOFILES=\
	datastore.go\
	doc.go\	
	error.go\
	iterator.go\
	key.go\
	load.go\
	prop.go\
	query.go\
	save.go\
	transaction.go\

include ${GOROOT}/src/Make.pkg
